{% set version = "0.4.0" %}

package:
  name: deckbridge
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/deckbridge/deckbridge-{{ version }}.tar.gz
  sha256: 6404ed7e8fbc786472f0b075ca5b517717160c824df6ce5c672dc4a791c9d8b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - pip
  run:
    - python >={{ python_min }}
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-auth-oauthlib
    - pandas
    - python-pptx

test:
  imports:
    - deckbridge
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/deckbridge/
  summary: Deck builder for analytics.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josephcobb111
